# Copyright (C) 2020-2022 Mitsubishi Electric Research Laboratories (MERL)
#
# SPDX-License-Identifier: AGPL-3.0-or-later

experiment_name: maskinf_experiment_a1
description: training a maskinf at the top level for guitar/strings/keyboards
output_dir: a1_maskinf_guitar_lvl1
code_dir: "/home/emanilow/hierarchical/testbed"
main_script: train.py

parameters:
  # ---- Paths
  slakh_base_dir: "/home/emanilow/slakh/slakh2100_16k_split"
  hierarchy_file: "/home/emanilow/hierarchical/testbed/hierarchical_defs/ismir_hierarchy.json"
  train_saliency_file: "/home/emanilow/hierarchical/saliency_files/train.json"
  val_saliency_file: "/home/emanilow/hierarchical/saliency_files/val.json"
  test_saliency_file: "/home/emanilow/hierarchical/saliency_files/test.json"

  # ---- Data preprocessing parameters (making the saliency file)
  chunk_duration: 10
  chunk_hop_ratio: 0.25
  saliency_threshold: -30.0
  saliency_threads: 4

  # ---- Dataset parameters
  #       list of instruments or just one, should match entry in hierarchy
  instruments: superlevel_strings_guitar_keyboards
  input_feature: "logmag"
  num_workers: 50
  frame_return: all
  num_other_sources: -1  # -1 means every other source

  # ---- STFT parameters
  sample_rate: 16000
  fft_frame_size: 1024
  fft_hop: 512

  # ---- Training parameters
  seed: 588
  batch_size: 25
  epochs: 100
  frames_per_sample: 400
  train_iterations: 20000
  val_iterations: 3000
  model_save_dir: models
  autoclip_percentile: 10

  # ---- Model parameters
  model_name: "maskinf"
  net_arch: "blstm"
  n_layers: 4
  n_hidden: 600
  dropout: 0.3
  mask_nonlinearity: sigmoid
  embed_nonlinearity: None
  embedding_dim: 20

  # ---- Target parameters
  loss_type: "qbe_anchor_dan"
  mask_loss: "l1"
  target_type: "psa"
  target_trunc_max: 1.0

  # ---- Optimizer parameters
  optimizer: "adam"
  alpha: 0.0001
  beta1: 0.9
  beta2: 0.999
  lr_decay: 0.5
  eps: 1e-08
  permitted_violations: 5

  # ---- Test parameters
  test_subset_saliency_file: "/home/emanilow/hierarchical/saliency_files/a1_test_set.json"
  test_iterations: 3000  # number of chunks for test (same size as saliency_chunks)
  tt_threads: 75
